name: Update snapshots

on:
  # Run any time any issue has a new comment on (this includes PRs)
  issue_comment:
    types: [created]

jobs:
  slash_command:
    name: slash command
    # This job will only run if the comment was on a pull requests and matches the slash command
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/update-snapshots'}}
    # Common with standard build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Get the branch the PR is associated to and hop into it
      - name: Get Branch
        id: getbranch
        run: |
          branch=$(\
            curl \
              -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }} \
            | jq -r '.head.ref')
          echo "::set-output name=branch::$branch"
      - name: Checkout tag/branch
        run: git checkout ${{ steps.getbranch.outputs.branch }}
      # Continue with standard build
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      # Update the snapshots
      - name: Update snapshots
        run: npx playwright test --update-snapshots --reporter=list
      # Commit the changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update snapshots

